### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by guofeng97** [iRB-Lab/N-Back#1] opened 2023-01-08 02:56 UTC
Beacause the website can not be correct right now, so I download the code to run on my laptop. But the problem came out: ReferenceError: generateTaskBlocks is not defined
    at Object.<anonymous> (D:\Lab\N-Back-master\N-Back-master\assets\js\run-task.js:3:14). 
Every function had this problem.

**Comment by iROCKBUNNY** [comment] 2023-01-08 17:50
@GuoFeng97 Thanks for your report! The issue is caused by wrong assets links, which were fixed in recent commit. The website is still available. If you want to run it on local machine, make sure to install a ruby envrionment and run it using jekyll bundler.

**Closed as completed by iROCKBUNNY** 2023-01-08 17:50 UTC
Labels: bug, question

**Comment by guofeng97** [comment] 2023-01-09 03:52
Thanks for your reply！I am really appreciated for that. But I found that the website can not record the result anymore, and there is no sound when I push the button below. I want to use this n-back experiment to finish my graduation paper, so could you please check it up for me? Thanks a lot! I am looking forward to your reply.

**Comment by iROCKBUNNY** [comment] 2023-01-09 06:12
@GuoFeng97 I see no problems! Perhaps it is your problem. Good luck to you paper.

**Comment by guofeng97** [comment] 2023-01-09 08:59
Thanks! I got it!
